FROM python:3.11-slim

WORKDIR /backend

RUN apt-get update && apt-get install -y --no-install-recommends libmagic1 && rm -rf /var/lib/apt/lists/*

COPY ./backend/requirements.txt .

# RUN is during the build
RUN pip install -r requirements.txt --no-cache-dir

COPY ./backend .

EXPOSE 8000

# CMD is when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]